
BylateBYLATE@a553771bfcd71759bf3b051f41614fb37f11043d2f5d0f452b0d9af894a0b45e"'
%https://github.com/weintsx/extensionsª±
ú
Kagane(eu.kanade.tachiyomi.extension.all.kagane§
Xhttps://cdn.jsdelivr.net/gh/weintsx/extensions@main/apk/tachiyomi-all.kagane-v1.6.32.apkjhttps://cdn.jsdelivr.net/gh/weintsx/extensions-source@main/src/all/kagane/res/mipmap-xhdpi/ic_launcher.pngª^https://raw.githubusercontent.com/weintsx/extensions/main/jar/tachiyomi-all.kagane-v1.6.32.jar"1.6( 21.6.328B)ì³Õ¹¸˜¯í7Kaganeen"https://kagane.toB)‘í¿§êÀˆKaganeja"https://kagane.toB)†ôªç×Á¿ğKaganeko"https://kagane.toB)ëĞº‹Ãÿ»Kaganezh"https://kagane.toB)ó£ú—¹¨§WKaganees"https://kagane.toB-ÿµ„¤ë×‹-Kaganees-419"https://kagane.toB)Õ¤»¸·Ê§TKaganefr"https://kagane.toB)ÌÕ½ìÚ¥·ÁKaganede"https://kagane.toB)®ü¥ı¢ÚÅ-Kaganept"https://kagane.toB,Úİ©œ¡İâö{Kaganept-BR"https://kagane.toB)øã„’ëºæ¹yKaganeru"https://kagane.toB)Åı ³œ×ûµKaganeit"https://kagane.toB)ÁÏñŒ¾àŸòjKaganeid"https://kagane.toB)«–¨é‹‘×zKaganevi"https://kagane.toB)Ó³¤¸ÔÖìKaganeth"https://kagane.toB)¡˜Ğ“©ÑŸÿKaganepl"https://kagane.toB)°·ÎÓ×²‘}Kaganehi"https://kagane.toB)‹áÄ×åÊmKaganear"https://kagane.to
Ê
NHentai)eu.kanade.tachiyomi.extension.all.nhentaiª
Yhttps://cdn.jsdelivr.net/gh/weintsx/extensions@main/apk/tachiyomi-all.nhentai-v1.4.57.apkkhttps://cdn.jsdelivr.net/gh/weintsx/extensions-source@main/src/all/nhentai/res/mipmap-xhdpi/ic_launcher.pngª_https://raw.githubusercontent.com/weintsx/extensions/main/jar/tachiyomi-all.nhentai-v1.4.57.jar"1.4(921.4.578B6öõ²„õÕİNHentai (english)en"https://nhentai.netB7»ÃçÎÜÓõ‹NHentai (japanese)ja"https://nhentai.netB6Â½êßí‘˜åNHentai (chinese)zh"https://nhentai.netB-ÜıÂßæĞø¸eNHentaiall"https://nhentai.net
ˆ
Webtoons.com*eu.kanade.tachiyomi.extension.all.webtoons­
Zhttps://cdn.jsdelivr.net/gh/weintsx/extensions@main/apk/tachiyomi-all.webtoons-v1.4.57.apklhttps://cdn.jsdelivr.net/gh/weintsx/extensions-source@main/src/all/webtoons/res/mipmap-xhdpi/ic_launcher.pngª`https://raw.githubusercontent.com/weintsx/extensions/main/jar/tachiyomi-all.webtoons-v1.4.57.jar"1.4(921.4.578B6Ø±üìõÙÈ€#Webtoons.comen"https://www.webtoons.comB6Ê®Å®áîº¶yWebtoons.comid"https://www.webtoons.comB6çÑìÏ”æœ.Webtoons.comth"https://www.webtoons.comB6‡½ÒˆãçÔŸxWebtoons.comes"https://www.webtoons.comB6äûÒ©–ÍˆÂrWebtoons.comfr"https://www.webtoons.comB;˜ÖÓ—†‹ş‰)Webtoons.comzh-Hant"https://www.webtoons.comB6£ƒ‰¶±¯ÑWebtoons.comde"https://www.webtoons.com
±
Comix&eu.kanade.tachiyomi.extension.en.comix¡
Vhttps://cdn.jsdelivr.net/gh/weintsx/extensions@main/apk/tachiyomi-en.comix-v1.4.35.apkhhttps://cdn.jsdelivr.net/gh/weintsx/extensions-source@main/src/en/comix/res/mipmap-xhdpi/ic_launcher.pngª\https://raw.githubusercontent.com/weintsx/extensions/main/jar/tachiyomi-en.comix-v1.4.35.jar"1.4(#21.4.358BK˜şßç‰†ÖÍhComixen"https://comix.to*https://comix.to*https://comix.ws
¥
	The Blank)eu.kanade.tachiyomi.extension.en.theblankª
Yhttps://cdn.jsdelivr.net/gh/weintsx/extensions@main/apk/tachiyomi-en.theblank-v1.4.57.apkkhttps://cdn.jsdelivr.net/gh/weintsx/extensions-source@main/src/en/theblank/res/mipmap-xhdpi/ic_launcher.pngª_https://raw.githubusercontent.com/weintsx/extensions/main/jar/tachiyomi-en.theblank-v1.4.57.jar"1.4(921.4.578B/Ï³®äÎñ×¤h	The Blanken"https://theblank.net